name: xml_schema_builder
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'
# homepage: https://www.example.com

environment:
  sdk: ^3.9.2

dependencies:
  xml: ^6.3.0

  json_annotation: ^4.5.0
  xml_schema_validator:
    path: ../xml_schema_validator

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

  analyzer: ^4.1.0
  build_test: ^2.1.0
  source_gen: ^1.2.2
  build: ^2.3.0
  glob: ^2.0.2
  json_serializable: ^6.1.4
