name: danfe_nfe
description: DANFE (Documento Auxiliar da Nota Fiscal Eletrônica) PDF generator for Brazilian NF-e.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.0.0

dependencies:
  intl: any
  pdf: ^3.8.4
  barcode: ^2.2.3
  nfe_client:
    path: ../nfe_client

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
